### ISSUE TITLE
Hot fix, sqlfluff for windows

### ISSUE THREAD

**Issue by dmf95** [bicks-bapa-roob/dbt-nhl-breakouts#28]
Expected behaviour
----
* Be able to run `sqlfluff fix models/analytics/core/f_player_season.sql` or the `tox` equivalent from a windows machine

Error
---
* `UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3593: character maps to <undefined>`

Steps to reproduce
---
1. Setup fresh conda environment on `python=3.8.12`
`conda create -n dbt-nhl-breakouts python=3.8.12`
2. Activate conda
`conda activate dbt-nhl-breakouts`
3. Install dependencies
`pip install dbt-bigquery`
`pip install sqlfluff-templater-dbt`
4. Attempt to lint or fix a query
`sqlfluff fix models/analytics/core/f_player_season.sql`

**Comment by dmf95** [comment]
Stuff we've tried to no avail
---
* New python versions
* Uninstalling potentially conflicting libraries
* Creating a `.sqlfluff` file in the root directory with the configs `[sqlfluff]\ntemplater = dbt`

**Comment by gavh3** [comment]
Closed by #30 and #32
