### ISSUE TITLE
Make github repo for documentation of shiz (private)

### ISSUE THREAD

**Issue by dmf95** [bicks-bapa-roob/dbt-nhl-breakouts#33]

**Comment by gavh3** [comment]
Documentation ideas from a data/analytics engineering perspective:
- where the data comes from
- how do we run the actions nhl-workflows to ingest NHL data into BigQuery
- basic dbt commands

**Comment by gavh3** [comment]
@dmf95 I think there is an opportunity to combine this with https://github.com/bicks-bapa-roob/nhl-breakouts/issues/2

**Comment by dmf95** [comment]
https://bicks-bapa-roob.github.io/
